version: '2'
services:
    saoluiz-app:
        image: saoluiz
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://saoluiz-mariadb:3306/saoluiz
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    saoluiz-mariadb:
        extends:
            file: mariadb.yml
            service: saoluiz-mariadb
